/**
 * @fileoverview Recommendations feature page.
 * @description Allows the user to select a registered user and view their personalized
 * movie recommendations generated by the collaborative filtering algorithm.
 * Supports a configurable top-N result count.
 */
import { useState } from 'react'
import { Film } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '../../shared/components/PageHeader'
import { LoadingSpinner } from '../../shared/components/LoadingSpinner'
import { EmptyState } from '../../shared/components/EmptyState'
import { Select } from '../../shared/components/ui/Select'
import { UserSelector } from '../../users/components/UserSelector'
import { useRecommendations } from '../hooks/useRecommendations'
import { RecommendationList } from '../components/RecommendationList'

/**
 * Full-page view for the recommendations section.
 * Renders a user selector and a result-count control; once a user is chosen
 * the recommendation list is fetched and displayed as ranked cards.
 */
export default function RecommendationsPage() {
  const { t } = useTranslation()
  const [selectedUserId, setSelectedUserId] = useState<string | null>(null)
  const [topN, setTopN] = useState<number>(5)

  const TOP_N_OPTIONS = [
    { value: '5',  label: `Top 5` },
    { value: '10', label: `Top 10` },
    { value: '15', label: `Top 15` },
  ]

  const { data: recommendations, isLoading, isError, error } = useRecommendations(
    selectedUserId,
    topN,
  )

  return (
    <div>
      <PageHeader
        title={t('pages:recommendations_title')}
        description={t('pages:recommendations_desc')}
      />

      <div className="flex flex-col sm:flex-row gap-4 mb-8">
        <div className="flex-1 max-w-sm">
          <UserSelector selectedUserId={selectedUserId} onSelect={setSelectedUserId} />
        </div>
        <div className="w-40 shrink-0">
          <Select
            label={t('common:results_label')}
            options={TOP_N_OPTIONS}
            value={String(topN)}
            onChange={(v) => setTopN(Number(v))}
          />
        </div>
      </div>

      {!selectedUserId && (
        <EmptyState
          title={t('common:empty_select_user')}
          description={t('common:choose_user_desc')}
          icon={<Film size={40} />}
        />
      )}

      {selectedUserId && isLoading && (
        <LoadingSpinner message={t('common:computing_recommendations')} />
      )}

      {selectedUserId && isError && (
        <div className="rounded-xl border border-red-800 bg-red-900/20 px-5 py-4">
          <p className="text-sm font-medium text-red-400">{t('common:error_load_recommendations')}</p>
          {error?.message && (
            <p className="mt-1 text-xs text-red-500">{error.message}</p>
          )}
        </div>
      )}

      {selectedUserId && !isLoading && !isError && recommendations?.length === 0 && (
        <EmptyState
          title={t('common:no_recommendations_title')}
          description={t('common:no_recommendations_desc')}
          icon={<Film size={40} />}
        />
      )}

      {selectedUserId && !isLoading && !isError && recommendations && recommendations.length > 0 && (
        <RecommendationList recommendations={recommendations} />
      )}
    </div>
  )
}
